#!/usr/bin/env python3
"""Behavior tests for the runnable demo, using its real launchers and Git store."""

import json
from pathlib import Path
import subprocess
import tempfile

import jsonschema

ROOT = Path(__file__).resolve().parents[1]
DEMO = ROOT / "examples/cooperating-workers/demo.sh"
SCHEMA = jsonschema.Draft202012Validator(json.loads((ROOT / "schema/git-locks.schema.json").read_text()))


def lines(root, name):
    return [json.loads(line) for line in (root / "receipts" / name).read_text().splitlines() if line.strip()]


def verify(root):
    receipts = root / "receipts"
    for path in receipts.glob("*.jsonl"):
        for record in lines(root, path.name):
            SCHEMA.validate(record)
    lifecycle = lines(root, "worker-a.jsonl")
    acquired, released = lifecycle[0], lifecycle[-1]
    assert acquired["event"] == "claimed" and acquired["holder"] == "alice"
    assert acquired["paths"] == ["generated/api.txt", "generated/types.txt"]
    assert released["event"] == "released" and released["job"] == "build"
    entered = lines(root, "worker-a-entered.jsonl")[0]
    assert entered["acquisition"] == acquired["acquisition"] and entered["state"] == "live"
    refusals = lines(root, "worker-b-refusal.jsonl")
    assert refusals and all(r["holder"] == "alice" and r["note"] == "regenerating API and types" for r in refusals)
    assert not (root / "work" / "blocked-ran").exists(), "refused mutation ran"
    during = lines(root, "independent-during.jsonl")[0]
    assert during["state"] == "live" and during["acquisition"] == acquired["acquisition"]
    assert (root / "work" / "independent.txt").read_text() == "unrelated work completed\n"
    before = lines(root, "before-renewal.jsonl")[0]
    after = lines(root, "after-renewal.jsonl")[0]
    assert before["record"] != after["record"]
    assert before["acquisition"] == after["acquisition"] == acquired["acquisition"]
    assert after["expires"] > before["expires"]
    assert all(r["state"] == "free" for r in lines(root, "after-worker-a.jsonl"))
    for name in ("api.txt", "types.txt"):
        assert (root / "work/generated" / name).read_text() == "generated by alice\n"
    old = lines(root, "superseded-worker.jsonl")
    replacement = lines(root, "replacement.jsonl")[0]
    survivor = lines(root, "replacement-survives.jsonl")[0]
    assert old[-1] == {"event": "nothing", "job": "reused", "reason": "superseded"}
    assert old[0]["acquisition"] != replacement["acquisition"] == survivor["acquisition"]
    assert survivor["holder"] == "bob" and survivor["state"] == "live"
    assert (receipts / "failing-worker.status").read_text().strip() == "17"
    assert lines(root, "failing-worker.jsonl")[-1]["event"] == "released"
    assert lines(root, "after-failure.jsonl")[0]["state"] == "free"
    expired = lines(root, "expired-while-running.jsonl")[0]
    assert expired["state"] == "expired" and expired["remaining"] == 0
    assert (receipts / "worker-active-after-expiry.txt").read_text().strip() == "yes"
    assert lines(root, "ttl-worker.jsonl")[-1]["event"] == "released"
    assert lines(root, "final-list.jsonl") == []
    assert lines(root, "final-doctor.jsonl")[-1]["healthy"] is True
    assert (receipts / "version.jsonl").exists()
    assert (receipts / "source-revision.txt").read_text().strip()


def run(output):
    result = subprocess.run(["bash", str(DEMO), str(output)], cwd=ROOT, text=True, capture_output=True, timeout=45)
    assert result.returncode == 0, (result.returncode, result.stdout, result.stderr)
    verify(output)


with tempfile.TemporaryDirectory(prefix="git-locks-demo-tests-") as tmp:
    scratch = Path(tmp)
    run(scratch / "golden path with spaces")
    # Existing caller-owned output is rejected before anything is overwritten.
    occupied = scratch / "occupied"
    occupied.mkdir()
    (occupied / "sentinel").write_text("keep me")
    result = subprocess.run(["bash", str(DEMO), str(occupied)], text=True, capture_output=True, timeout=10)
    assert result.returncode == 2 and (occupied / "sentinel").read_text() == "keep me"
    assert sorted(p.name for p in occupied.iterdir()) == ["sentinel"]
    # Two complete demonstrations overlap in time but use separate stores.
    runs = []
    for index in range(2):
        output = scratch / f"parallel-{index}"
        proc = subprocess.Popen(["bash", str(DEMO), str(output)], cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        runs.append((proc, output))
    for proc, output in runs:
        stdout, stderr = proc.communicate(timeout=60)
        assert proc.returncode == 0, (proc.returncode, stdout, stderr)
        verify(output)
    print("cooperating-worker demo: golden path, lifecycle edges, failure/expiry/supersession and 2 concurrent isolated runs passed")
