#!/usr/bin/env python3
"""Behavior tests for the runnable demo, using its real launchers and Git store."""

from pathlib import Path as _GuardPath
import subprocess as _guard_subprocess
_guard_subprocess.run(["node", str(_GuardPath(__file__).resolve().parents[1] / "scripts/require-docker.mjs")], check=True)

import argparse
import hashlib
import json
import os
from pathlib import Path
import signal
import subprocess
import tempfile
import time

import jsonschema

ROOT = Path(__file__).resolve().parents[1]
DEMO = ROOT / "examples/cooperating-workers/demo.sh"
RECORDED = ROOT / "examples/cooperating-workers/recorded-run.json"
SCHEMA = jsonschema.Draft202012Validator(json.loads((ROOT / "schema/git-locks.schema.json").read_text()))


def lines(root, name):
    return [json.loads(line) for line in (root / "receipts" / name).read_text().splitlines() if line.strip()]


def start_demo(output):
    # Its own session, so a stop reaches the background launchers and gated workers too.
    return subprocess.Popen(["bash", str(DEMO), str(output)], cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, start_new_session=True)


def group_alive(pgid):
    try:
        os.killpg(pgid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:  # macOS: only exited members awaiting their reaper remain
        return False
    return True


def session_members(sid):
    members = []
    for stat in Path('/proc').glob('[0-9]*/stat'):
        try:
            fields = stat.read_text().rsplit(')', 1)[1].split()
            if fields[0] != 'Z' and int(fields[3]) == sid:
                members.append(int(stat.parent.name))
        except FileNotFoundError:
            pass
    return members


def stop_demo(proc):
    # Request the launcher's EXIT cleanup, then reclaim only its owned session.
    if proc.poll() is None:
        proc.terminate()
        try:
            proc.wait(timeout=8)
        except subprocess.TimeoutExpired:
            pass
    for pid in session_members(proc.pid):
        try:
            os.kill(pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
    proc.wait(timeout=5)


def finish_demo(proc, timeout):
    try:
        stdout, stderr = proc.communicate(timeout=timeout)
    finally:
        stop_demo(proc)
    return stdout, stderr


def verify(root):
    receipts = root / "receipts"
    for path in receipts.glob("*.jsonl"):
        for record in lines(root, path.name):
            SCHEMA.validate(record)
    lifecycle = lines(root, "worker-a.jsonl")
    acquired, released = lifecycle[0], lifecycle[-1]
    assert acquired["event"] == "claimed" and acquired["holder"] == "alice"
    assert acquired["paths"] == ["generated/api.txt", "generated/types.txt"]
    assert released["event"] == "released" and released["job"] == "build"
    entered = lines(root, "worker-a-entered.jsonl")[0]
    assert entered["acquisition"] == acquired["acquisition"] and entered["state"] == "live"
    refusals = lines(root, "worker-b-refusal.jsonl")
    assert refusals and all(r["holder"] == "alice" and r["note"] == "regenerating API and types" for r in refusals)
    assert not (root / "work" / "blocked-ran").exists(), "refused mutation ran"
    during = lines(root, "independent-during.jsonl")[0]
    assert during["state"] == "live" and during["acquisition"] == acquired["acquisition"]
    assert (root / "work" / "independent.txt").read_text() == "unrelated work completed\n"
    before = lines(root, "before-renewal.jsonl")[0]
    after = lines(root, "after-renewal.jsonl")[0]
    assert before["record"] != after["record"]
    assert before["acquisition"] == after["acquisition"] == acquired["acquisition"]
    assert after["expires"] > before["expires"]
    assert all(r["state"] == "free" for r in lines(root, "after-worker-a.jsonl"))
    for name in ("api.txt", "types.txt"):
        assert (root / "work/generated" / name).read_text() == "generated by alice\n"
    old = lines(root, "superseded-worker.jsonl")
    replacement = lines(root, "replacement.jsonl")[0]
    survivor = lines(root, "replacement-survives.jsonl")[0]
    assert old[-1] == {"event": "lost", "job": "reused", "reason": "superseded",
                       "acquisition": old[0]["acquisition"], "command_status": 0}
    assert (receipts / "superseded-worker.status").read_text().strip() == "125"
    assert old[0]["acquisition"] != replacement["acquisition"] == survivor["acquisition"]
    assert survivor["holder"] == "bob" and survivor["state"] == "live"
    assert (receipts / "failing-worker.status").read_text().strip() == "17"
    assert lines(root, "failing-worker.jsonl")[-1]["event"] == "released"
    assert lines(root, "after-failure.jsonl")[0]["state"] == "free"
    expired = lines(root, "expired-while-running.jsonl")[0]
    assert expired["state"] == "expired" and expired["remaining"] == 0
    assert (receipts / "worker-active-after-expiry.txt").read_text().strip() == "yes"
    assert lines(root, "ttl-worker.jsonl")[-1]["event"] == "released"
    assert lines(root, "final-list.jsonl") == []
    assert lines(root, "final-doctor.jsonl")[-1]["healthy"] is True
    assert (receipts / "version.jsonl").exists()
    assert (receipts / "source-revision.txt").read_text().strip()


def normalized(records, run_directory):
    identities = {key: {} for key in ('acquisition', 'record', 'root')}

    def visit(value, key=None):
        if isinstance(value, dict):
            return {name: visit(value[name], name) for name in sorted(value)}
        if isinstance(value, list):
            return [visit(item) for item in value]
        if isinstance(value, str):
            if key in identities:
                seen = identities[key]
                if value not in seen:
                    seen[value] = f'{key}-{len(seen)}'
                return seen[value]
            return value.replace(str(run_directory), '<run>')
        return value

    return visit(records)


def verify_recorded(root, stdout):
    # The retained run must still describe what the demo emits today.
    recorded = json.loads(RECORDED.read_text())
    records = recorded["cli_records"]
    assert sorted(records) == sorted(p.name for p in (root / "receipts").glob("*.jsonl")), "recorded receipt set drifted"
    for batch in records.values():
        for record in batch:
            SCHEMA.validate(record)
    assert sum(len(batch) for batch in records.values()) == recorded["schema_validated_records"]
    assert recorded["transcript"][:-1] == stdout.splitlines()[:-1], "recorded transcript drifted"
    archived_root = Path(records['store.jsonl'][0]['store']).parent
    actual = {p.name: lines(root, p.name) for p in (root / 'receipts').glob('*.jsonl')}
    assert normalized(records, archived_root) == normalized(actual, root), 'recorded behavior or identity relationships drifted'
    assert recorded['superseded_worker_status'] == 125


def run(output):
    proc = start_demo(output)
    stdout, stderr = finish_demo(proc, 45)
    assert proc.returncode == 0, (proc.returncode, stdout, stderr)
    verify(output)
    return stdout


def stopped_demo_leaves_no_workers(output):
    proc = start_demo(output)
    try:
        ready = output / "gates" / "build.ready"
        deadline = time.monotonic() + 30
        while not ready.exists():
            assert proc.poll() is None and time.monotonic() < deadline, "demo never gated its first worker"
            time.sleep(0.02)
        proc.terminate()
        assert proc.wait(timeout=8) == 143
        deadline = time.monotonic() + 5
        while session_members(proc.pid) and time.monotonic() < deadline:
            time.sleep(.02)
        assert not session_members(proc.pid), "stopped demo left a process in its session"
        result = subprocess.run([str(ROOT / 'bin/git-locks'), 'list'], text=True, capture_output=True, timeout=5,
                                env=dict(os.environ, GIT_LOCKS_STORE=str(output / 'store.git'), GIT_LOCKS_NOW='1000000'))
        assert result.returncode == 0 and not result.stdout, result
    finally:
        stop_demo(proc)


def write_recorded(root, stdout, output):
    records = {p.name: lines(root, p.name) for p in sorted((root / 'receipts').glob('*.jsonl'))}
    report = {
        'artifacts': {name: (root / 'work' / name).read_text() for name in
                      ('failed.txt', 'generated/api.txt', 'generated/types.txt', 'independent.txt')},
        'blocked_mutation_ran': (root / 'work/blocked-ran').exists(),
        'cli_records': records,
        'clock': {'default': 1000000, 'expiry_observation': 1000002, 'kind': 'simulated'},
        'external_adoption': 'not run',
        'failing_worker_status': int((root / 'receipts/failing-worker.status').read_text()),
        'superseded_worker_status': int((root / 'receipts/superseded-worker.status').read_text()),
        'schema_validated_records': sum(len(batch) for batch in records.values()),
        'source_revision': (root / 'receipts/source-revision.txt').read_text().strip(),
        'source_revision_kind': 'synthetic copied-input commit, with no upstream history',
        'source_sha256': {name: hashlib.sha256((ROOT / name).read_bytes()).hexdigest() for name in
                          ('bin/git-locks', 'examples/cooperating-workers/demo.sh', 'examples/cooperating-workers/worker.sh')},
        'transcript': stdout.splitlines(),
        'worker_active_after_expiry': (root / 'receipts/worker-active-after-expiry.txt').read_text().strip() == 'yes',
    }
    with output.open('x') as stream:
        stream.write(json.dumps(report, indent=2, sort_keys=True) + '\n')


parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--record', type=Path, help='export this observed golden run to a fresh JSON file')
args = parser.parse_args()


with tempfile.TemporaryDirectory(prefix="git-locks-demo-tests-") as tmp:
    scratch = Path(tmp)
    golden = scratch / "golden path with spaces"
    transcript = run(golden)
    if args.record:
        write_recorded(golden, transcript, args.record)
    else:
        verify_recorded(golden, transcript)
    # Existing caller-owned output is rejected before anything is overwritten.
    occupied = scratch / "occupied"
    occupied.mkdir()
    (occupied / "sentinel").write_text("keep me")
    result = subprocess.run(["bash", str(DEMO), str(occupied)], text=True, capture_output=True, timeout=10, check=False)
    assert result.returncode == 2 and (occupied / "sentinel").read_text() == "keep me"
    assert sorted(p.name for p in occupied.iterdir()) == ["sentinel"]
    stopped_demo_leaves_no_workers(scratch / "stopped")
    # Two complete demonstrations overlap in time but use separate stores.
    runs = [(start_demo(scratch / f"parallel-{index}"), scratch / f"parallel-{index}") for index in range(2)]
    try:
        for proc, output in runs:
            stdout, stderr = proc.communicate(timeout=60)
            assert proc.returncode == 0, (proc.returncode, stdout, stderr)
            verify(output)
    finally:
        for proc, _ in runs:
            stop_demo(proc)
    print("cooperating-worker demo: golden path, recorded run, lifecycle edges, failure/expiry/supersession, stop cleanup and 2 concurrent isolated runs passed")
