#!/usr/bin/env bash
# Invoked by the demo launcher through git-locks with, after admission.
set -euo pipefail
DEMO_BIN="${DEMO_BIN:?the launcher sets the executable}"
DEMO_RECEIPTS="${DEMO_RECEIPTS:?the launcher sets the receipt directory}"
label="$1" job="$2" gate="$3" mode="$4"
"${DEMO_BIN}" show --job "${job}" >"${DEMO_RECEIPTS}/${label}-entered.jsonl"
case "${mode}" in
  build)
    printf 'generated by alice\n' >generated/api.txt
    printf 'generated by alice\n' >generated/types.txt
    ;;
  independent)
    "${DEMO_BIN}" show --job build >"${DEMO_RECEIPTS}/independent-during.jsonl"
    printf 'unrelated work completed\n' >independent.txt
    exit 0
    ;;
  failure)
    printf 'partial output before failure\n' >failed.txt
    exit 17
    ;;
  superseded | ttl) ;;
  *) exit 2 ;;
esac
: >"${gate}.ready"
for ((attempt = 0; attempt < 1500; attempt++)); do
  [[ ! -e "${gate}" ]] || exit 0
  sleep 0.02
done
printf 'worker timed out waiting for %s\n' "${gate}" >&2
exit 1
